version: '3.3'

services:
  user:
    build: ./User
    container_name: user
    ports:
      - "8080:8080"
    networks:
      - ego-network
    volumes:
      - ./User:/usr/go/src/
    depends_on:
      - mysql
    
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ego"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    tty: true
    restart: always
    command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    networks:
      - ego-network
    volumes:
      - ./mysql:/var/lib/mysql
    # depends_on:
    #   - redis

networks:
  ego-network:
    driver: bridge